# Generated by Django 4.1.1 on 2022-10-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
    ]
