# Generated by Django 4.1.1 on 2022-10-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_parent_content_type_category_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="category",
            name="object_id",
        ),
    ]
