# Generated by Django 4.1.1 on 2022-11-09 20:59

import blog.validators
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_newsletter_alter_bookmark_user"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=300, verbose_name="نام به انگلیسی"),
                ),
                (
                    "name_fa",
                    models.CharField(max_length=300, verbose_name="نام به فارسی"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="شناسه"),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="توضحیات")),
                (
                    "preview",
                    models.CharField(
                        default="", max_length=500, verbose_name="پیش نمایش"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="media/book/",
                        validators=[blog.validators.validate_cover],
                        verbose_name="عکس",
                    ),
                ),
                (
                    "vpn",
                    models.BooleanField(
                        default=False, verbose_name="آیا نیاز به vpn دارد ؟"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="categories",
                        to="core.category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="book_like",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="لایک ها",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب",
                "verbose_name_plural": "کتاب ها",
                "ordering": ["-id"],
            },
        ),
    ]
