# Generated by Django 4.1.1 on 2022-11-17 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateTimeField(auto_now=True, verbose_name="کی ساخته شده ؟"),
        ),
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="کی اپدیت شده ؟",
            ),
            preserve_default=False,
        ),
    ]
