# Generated by Django 4.1.1 on 2022-10-25 19:14

import blog.validators
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="کی اپدیت شده ؟"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="کی ساخته شده ؟"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("name", models.CharField(max_length=250, verbose_name="نام")),
                ("description", models.TextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "لیست ها",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="کی اپدیت شده ؟"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="کی ساخته شده ؟"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="شناسه"),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="توضحیات")),
                (
                    "preview",
                    models.CharField(
                        default="", max_length=500, verbose_name="پیش نمایش"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="media/article/",
                        validators=[blog.validators.validate_cover],
                        verbose_name="عکس",
                    ),
                ),
                (
                    "vpn",
                    models.BooleanField(
                        default=False, verbose_name="آیا نیاز به vpn دارد ؟"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-id"],
            },
        ),
    ]
