# Generated by Django 4.1.1 on 2022-09-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="description",
            new_name="content",
        ),
    ]
