# Generated by Django 4.1.1 on 2022-09-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_description_article_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"verbose_name": "لیست ها"},
        ),
    ]
