# Generated by Django 4.1.1 on 2022-10-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_list_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
