# Generated by Django 4.1.1 on 2022-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_category_content_type_and_more"),
        ("blog", "0004_remove_article_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="articles", to="core.category", verbose_name="دسته بندی"
            ),
        ),
    ]
